// client/src/pages/index.vue
<script lang="ts">
import { useAuth } from '@client/stores/auth'
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'IndexPage',
})
</script>

<script setup lang="ts">
const auth = useAuth()
console.log(auth.current)
</script>

<template>
	<LayoutDefault>
		<LandingPage v-if="!auth.current" />
		<HomePage v-else />
	</LayoutDefault>
</template>

<style lang="scss" scoped></style>

// client/src/pages/index.tsx
import Page from '@client/components/Page';
import styles from './index.module.scss';
import { useAuth } from '@client/stores/auth';

export default function IndexPage() {
	const auth = useAuth();
	console.log('Index', auth.current);

	return (
		<Page className={styles.IndexPage}>
			<h1>Hello, IndexPage</h1>

			{auth.current && <p>Logged in as {auth.current}</p>}
		</Page>
	);
}
